name: publish-nuget

on:
  push:
    branches: [master]

env:
  DOTNET_NOLOGO: 1
  DOTNET_VERSION: 5.0.x

jobs:
  publish:
    runs-on: windows-latest
    env:
        PROJECT_FILE_PATH: src/ProtoUntyped/ProtoUntyped.csproj
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish NuGet on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ${{ env.PROJECT_FILE_PATH }}
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: true
