name: Publish NuGet package

on:
  push:
    branches: [master]

env:
  DOTNET_NOLOGO: 1

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        PROJECT_FILE_PATH: src/ProtoUntyped/ProtoUntyped.csproj

         # Stop wasting time caching packages
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

        # Disable sending usage data
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      
      - name: Install tools
        run: dotnet tool restore
        
      - name: Get project version
        id: project_version
        run: |
          versionValue=`dotnet version -f "${{ env.PROJECT_FILE_PATH }}" --output-format=json | head -n 1 | jq -r '.currentVersion'`
          echo ::set-output name=PROJECT_VERSION::$versionValue

      - name: Publish NuGet on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ${{ env.PROJECT_FILE_PATH }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false

      - name: Push tag
        run: |
          tag=v${{ steps.project_version.outputs.PROJECT_VERSION }}
          git tag $tag
          git push "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" $tag